#!/bin/bash

case `uname` in
  Linux) ECHO="echo -e" ;;
  *) ECHO="echo" ;;
esac

usage() {
  $ECHO "git datus [options]"
  $ECHO
  $ECHO "Options:"
  $ECHO "-u[mode]        \tshow untracked files (mode = no, normal, all)"
  $ECHO "-l,--long       \tshow long timestamp"
  $ECHO "-h,--help       \tshow this message and exit"
  exit 1
}

UARG=""
LONGTIME=""
while [ $# -gt 0 ]; do
  case $1 in 
    -u*)
      UARG=$1
      shift
      ;;
    -l|--long)
      LONGTIME=true
      shift
      ;;
    -h|--help)
      HELP=true
      shift
      ;;
    -*)
      $ECHO "Unknown option $1" ; exit 1 ;;
  esac
done
if [ "$HELP" == "true" ]; then
  usage
fi

# handles moved or deleted files, keeps track of staging
git status -s $UARG | while IFS= read -r; do 
  mode=${REPLY:0:2}
  unset IFS; read -r junk file <<< "$REPLY"
  afile=($file)
  nowfile=${afile[${#afile[@]}-1]}
  if [ -f $nowfile ]; then
    if [ -n "$LONGTIME" ]; then
      datestr=$(stat -c %y $nowfile)
    else
      datestr=$(date -d "$(stat -c %y $nowfile)" '+%F %T')
    fi
  else
    datestr="---"
  fi
  echo "$mode" "$datestr" "$file"
done | sort -k1.4
